#!/bin/bash

tlp-stat -c | grep -e "START_CHARGE_THRESH_BAT1" -e "STOP_CHARGE_THRESH_BAT1" | awk ' { print $3 } ' | awk -F'"' '{for(i=2; i<=NF; i+=2) print $i}' | awk '{printf (NR%2==0) ? $0 "%\n" : "tlp: " $0 "%-"}'
