#!/bin/bash

# This is temporarily disabled, as long as i see no way of delaying the suspend action until this commands finishes. The image, that i3lock is using is currently semi-static. It only gets generated by the `ulauncher` action `suspend`. (`ulauncher` invokes `script-lock-prepare-lockimage.sh` before `systemctl suspend`)

# flameshot full -c -p /tmp/raw_screen.png
# convert /tmp/raw_screen.png -blur 0x20 /tmp/blured_screen.png
# convert /tmp/blured_screen.png $HOME/.config/i3lock/lock.png -gravity NorthWest -composite -matte /tmp/lockscreen.png
