backend = "pulseaudio"
use_nerd_font = true
shuffle = true
repeat = "playlist"
hide_display_names = true

[keybindings]
"Space" = "pause"
"q" = ""


[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#8aadf4"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#41588c"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#8aadf4"
statusbar_bg = "#363a4f"
statusbar_progress = "#8aadf4"
cmdline = "#8aadf4"
cmdline_bg = "#1e2030"
